sudo: false
language: node_js
node_js:
  - 8
os:
  - linux
before_install:
  - npm i -g npm@5.6.0
  - npm --version
install:
  - npm i
  - npm i -g jest eslint codecov
before_script:
  - if [[ "$TRAVIS_BRANCH" == "master" || "$TRAVIS_BRANCH" == "develop" ]]; then gulp crowdin; fi
script:
  - eslint && jest --coverage
  - codecov
